<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RSI1535" ignored="0" name="Test" tests="5" failures="1" timestamp="06 Feb 2020 20:59:49 GMT" time="288.33" errors="0">
  <testcase name="teste" time="6.889" classname="br.com.rsinet.mobile.appium.testes.TesteTelaPrincipal"/>
  <testcase name="pesquisa1Produto_Invalido" time="3.317" classname="br.com.rsinet.mobile.appium.testes.TestePesquisaPorLupa"/>
  <testcase name="pesquisa2Produto_valido" time="5.421" classname="br.com.rsinet.mobile.appium.testes.TestePesquisaPorLupa"/>
  <testcase name="cadastro1Valido" time="39.551" classname="br.com.rsinet.mobile.appium.testes.TesteCadastro"/>
  <testcase name="cadastro2Invalido" time="37.961" classname="br.com.rsinet.mobile.appium.testes.TesteCadastro">
    <failure type="java.lang.AssertionError" message="Advantage expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Advantage expected [true] but found [false]
at br.com.rsinet.mobile.appium.testes.TesteCadastro.cadastro2Invalido(TesteCadastro.java:100)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- cadastro2Invalido -->
</testsuite> <!-- Test -->
