<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="29657" started-at="2020-02-02T18:04:18Z" finished-at="2020-02-02T18:04:48Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="29657" started-at="2020-02-02T18:04:18Z" finished-at="2020-02-02T18:04:48Z">
      <class name="br.com.AppiumMobile.TesteBuscadeprodutoNegativo">
        <test-method status="PASS" signature="report()[pri:0, instance:br.com.AppiumMobile.TesteBuscadeprodutoNegativo@55d56113]" name="report" is-config="true" duration-ms="142" started-at="2020-02-02T18:04:18Z" finished-at="2020-02-02T18:04:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- report -->
        <test-method status="PASS" signature="before()[pri:0, instance:br.com.AppiumMobile.TesteBuscadeprodutoNegativo@55d56113]" name="before" is-config="true" duration-ms="26240" started-at="2020-02-02T18:04:19Z" finished-at="2020-02-02T18:04:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="FAIL" signature="testes2()[pri:0, instance:br.com.AppiumMobile.TesteBuscadeprodutoNegativo@55d56113]" name="testes2" duration-ms="2694" started-at="2020-02-02T18:04:45Z" finished-at="2020-02-02T18:04:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at br.com.AppiumMobile.TesteBuscadeprodutoNegativo.testes2(TesteBuscadeprodutoNegativo.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testes2 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:br.com.AppiumMobile.TesteBuscadeprodutoNegativo@55d56113]" name="afterMethod" is-config="true" duration-ms="563" started-at="2020-02-02T18:04:48Z" finished-at="2020-02-02T18:04:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testes2 status=FAILURE method=TesteBuscadeprodutoNegativo.testes2()[pri:0, instance:br.com.AppiumMobile.TesteBuscadeprodutoNegativo@55d56113] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- br.com.AppiumMobile.TesteBuscadeprodutoNegativo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
